# Python environment
name: meteo473_fa20
channels:
  - conda-forge
dependencies:
  - python=3.7
  #
  # environment
  - ipython
  - ipykernel
  - ipympl  # brings notebook, etc.; for `%matplotlib widget` in Jupyter Lab/Notebook
  - jupytext
  - jupyterlab
  - nodejs
  #
  # data
  - netcdf4
  - h5netcdf  # depends on h5py
  - pyyaml
  - tabulate  # needed by pd.DataFrame.to_markdown()
  #
  # analysis, scientific tools
  - xarray
  - matplotlib
  - cartopy
  - scipy
  - statsmodels
  # - xesmf
  # - esmpy=7.1.0  # https://xesmf.readthedocs.io/en/latest/installation.html#install-on-local-machine-with-conda
  #
  # pangeo xesmf (not yet released) via pip
  - esmpy>=8.0.0  # ! not available for Windows
  - pip
  - pip:
    - git+https://github.com/pangeo-data/xESMF#egg=xesmf  # master
    # - git+https://github.com/pangeo-data/xESMF.git@v0.4.0#egg=xesmf  # last (GitHub) release
  #
  # dev tools
  - pylint
