# Python environment
name: meteo473_fa20
channels:
  - conda-forge
dependencies:
  - python=3.7
  #
  - ipython
  - ipykernel
  #
  - xarray
  - netcdf4
  - h5netcdf  # depends on h5py
  - pyyaml
  - tabulate  # needed by pd.DataFrame.to_markdown()
